apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: todo-backend
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-backend
  metrics:
  - type: Resource
    resource:
      name: todo-backend
      targetAverageUtilization: 50