apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  labels:
    app: todo-backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1      
      maxUnavailable: 0
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: ahmadulinjs/todoserver:latest
        resources:
          requests:
            cpu: "20m"
            memory: "50Mi"
          limits:
            cpu: "900m"
            memory: "900Mi"
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /status
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        env:
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: todo-mongo-secret
              key: MONGO_ROOT_USERNAME
        - name: MONGODB_PASS
          valueFrom:
            secretKeyRef:
              name: todo-mongo-secret
              key: MONGO_ROOT_PASSWORD
        - name: MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: todo-mongo-configmap
              key: MONGO_SERVER
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
spec:
  selector:
    app: todo-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30010