apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  labels:
    app: todo-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: todo-frontend
          image: ahmadulinjs/todoclient
          resources:
            limits:
              cpu: "50m"
              memory: "150Mi"
          ports:
            - containerPort: 80
              name: http-port
          env:
            - name: TODO_SERVER
              value: todo-backend-service 
  selector:
    matchLabels:
      app: todo-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: todo-frontend
  type: NodePort