apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-mongodb
  labels:
    app: todo-mongodb
spec:
  serviceName: todo-mongo-service
  replicas: 1
  selector:
    matchLabels:
      app: todo-mongodb
  template:
    metadata:
      labels:
        app: todo-mongodb
    spec:
      containers:
      - name: todo-mongodb
        image: mongo
        resources:
          limits:
            cpu: "900m"
            memory: "1Gi"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: todo-mongo-secret
              key: MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-mongo-secret
              key: MONGO_ROOT_PASSWORD
        volumeMounts:
          - name: data
            mountPath: /data/db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: todo-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: todo-mongo-service
spec:
  selector:
    app: todo-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
